<?php

/**
 * Report Model
 *
 * @since      1.0.0
 * @version    1.0.0
 */

namespace WPCOMSpecialProjects\Wayback_Link_Fixer\Report;

use DateTimeImmutable;

defined( 'ABSPATH' ) || exit;

/**
 * Report
 */
class Report {

	/**
	 * The report DB Id.
	 *
	 * @since 1.0.0
	 *
	 * @var integer
	 */
	private int $id;

	/**
	 * The report hash/id
	 *
	 * @since 1.0.0
	 *
	 * @var string
	 */
	private string $report_id;

	/**
	 * Report generated by user.
	 *
	 * @since 1.0.0
	 *
	 * @var integer
	 */
	private int $user_id;

	/**
	 * The blog ID report was generated for.
	 *
	 * @since 1.0.0
	 *
	 * @var integer
	 */
	private int $blog_id;


	/**
	 * Links auto fixed?
	 *
	 * @since 1.0.0
	 *
	 * @var boolean
	 */
	private bool $fixed;

	/**
	 * The current process.
	 *
	 * @since 1.0.0
	 *
	 * @var string
	 */
	private string $process = 'pending';

	/**
	 * The description
	 *
	 * @since 1.0.0
	 *
	 * @var string
	 */
	private string $description = '';

	/**
	 * Date the report was created.
	 *
	 * @since 1.0.0
	 *
	 * @var \DateTimeImmutable
	 */
	private \DateTimeImmutable $created_at;

	/**
	 * Date the report was completed.
	 *
	 * @since 1.0.0
	 *
	 * @var ?\DateTimeImmutable
	 */
	private ?\DateTimeImmutable $completed_at = null;

	/**
	 * Create instance of Report.
	 *
	 * @since 1.0.0
	 *
	 * @param integer     $id           The report DB Id.
	 * @param string      $report_id    The report hash/id.
	 * @param integer     $user_id      The user ID.
	 * @param integer     $blog_id      The blog ID.
	 * @param boolean     $fixed        Links auto fixed.
	 * @param string      $process      The current process.
	 * @param string      $description  The description.
	 * @param string      $created_at   Date the report was created.
	 * @param string|null $completed_at Date the report was completed.
	 */
	public function __construct(
		int $id,
		string $report_id,
		int $user_id,
		int $blog_id,
		bool $fixed,
		string $process,
		string $description,
		string $created_at,
		?string $completed_at = null
	) {
		$this->id          = $id;
		$this->report_id   = $report_id;
		$this->user_id     = $user_id;
		$this->blog_id     = $blog_id;
		$this->fixed       = $fixed;
		$this->process     = $process;
		$this->description = $description;
		$this->created_at  = \DateTimeImmutable::createFromFormat( 'Y-m-d H:i:s', $created_at ) ?: new DateTimeImmutable(); //phpcs:ignore Universal.Operators.DisallowShortTernary.Found
		if ( null !== $completed_at ) {
			$this->completed_at = \DateTimeImmutable::createFromFormat( 'Y-m-d H:i:s', $completed_at ) ?: null; //phpcs:ignore Universal.Operators.DisallowShortTernary.Found
		}
	}

	/**
	 * Get the report DB Id.
	 *
	 * @since 1.0.0
	 *
	 * @return integer
	 */
	public function get_id(): int {
		return $this->id;
	}

	/**
	 * Get the report hash/id.
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	public function get_report_id(): string {
		return $this->report_id;
	}

	/**
	 * Get the user ID.
	 *
	 * @since 1.0.0
	 *
	 * @return integer
	 */
	public function get_user_id(): int {
		return $this->user_id;
	}

	/**
	 * Get the blog ID.
	 *
	 * @since 1.0.0
	 *
	 * @return integer
	 */
	public function get_blog_id(): int {
		return $this->blog_id;
	}

	/**
	 * Get the fixed status.
	 *
	 * @since 1.0.0
	 *
	 * @return boolean
	 */
	public function get_fixed(): bool {
		return $this->fixed;
	}

	/**
	 * Get the process.
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	public function get_process(): string {
		return $this->process;
	}

	/**
	 * Get the description.
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	public function get_description(): string {
		return $this->description;
	}

	/**
	 * Get the created_at date.
	 *
	 * @since 1.0.0
	 *
	 * @return \DateTimeImmutable
	 */
	public function get_created_at(): \DateTimeImmutable {
		return $this->created_at;
	}

	/**
	 * Get the completed_at date.
	 *
	 * @since 1.0.0
	 *
	 * @return ?\DateTimeImmutable
	 */
	public function get_completed_at(): ?\DateTimeImmutable {
		return $this->completed_at;
	}
}
