name: Deploy to WordPress.org

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install DEV Deps, build i18n files
      - name: Run i18n Build
        run: |
          composer install --ignore-platform-reqs --no-interaction
          composer internationalize

      # Install PROD Deps
      - name: Install Composer Dependencies
        run: composer install --no-dev

      # Install Node Modules and Build Assets
      - name: Install Node Modules and Build Assets
        run: |
          npm install
          npm run build

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: internet-archive-wayback-machine-link-fixer
